services:
  - type: web
    name: backend
    plan: starter
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: markaz-media-db 
          property: connectionString 
      - key: GEMINI_API_KEY
        sync: false
      - key: RENDER_FRONTEND_URL
        fromService:
          type: web
          name: frontend
          property: host 

  - type: web
    name: frontend
    plan: starter
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: backend
          property: host 

  - type: web
    name: video-sync-service
    plan: starter
    env: docker
    dockerfilePath: ./services/video-synchronizer/Dockerfile
    dockerContext: ./services/video-synchronizer
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: news-refine-service
    plan: starter
    env: docker
    dockerfilePath: ./services/news-refine/Dockerfile
    dockerContext: ./services/news-refine
    envVars:
      - key: GEMINI_API_KEY
        sync: false
  
  - type: web
    name: avatar-service
    plan: starter
    env: docker
    dockerfilePath: ./services/dynamic-avatar/Dockerfile
    dockerContext: ./services/dynamic-avatar
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: chatbot-service
    plan: starter
    env: docker
    dockerfilePath: ./services/news-chatbot/Dockerfile
    dockerContext: ./services/news-chatbot
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: asharq-service
    plan: starter
    env: docker
    dockerfilePath: ./services/asharq-news/Dockerfile
    dockerContext: ./services/asharq-news
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: podcast-service
    plan: starter
    env: docker
    dockerfilePath: ./services/podcast-helper/Dockerfile
    dockerContext: ./services/podcast-helper
    envVars:
      - key: GEMINI_API_KEY
        sync: false
        
  - type: web
    name: style-editor-service
    plan: starter
    env: docker
    dockerfilePath: ./services/style-editor/Dockerfile
    dockerContext: ./services/style-editor
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MAIN_BACKEND_URL
        fromService:
          type: web
          name: backend
          property: host 
  - type: web
    name: infographic-service
    plan: starter
    env: docker
    dockerfilePath: ./services/infographic-converter/Dockerfile
    dockerContext: ./services/infographic-converter
    envVars:
      - key: GEMINI_API_KEY
        sync: false