import { GoogleGenerativeAI } from "@google/generative-ai";
import type { GeneratedResult, RecentNewsItem } from '../types';
import { GenerationMode } from "../types";

declare global {
  interface ImportMetaEnv {
    readonly VITE_GEMINI_API_KEY: string;
    readonly VITE_FACEBOOK_PAGE_ID: string;
    readonly VITE_FACEBOOK_PAGE_ACCESS_TOKEN: string;
  }
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }
}

// ✅ استخدام مفتاح API من Vite (Render يوفره عبر env)
const ai = new GoogleGenerativeAI(import.meta.env.VITE_GEMINI_API_KEY);

const DEFAULT_SOURCES = [
  'الجزيرة', 'العربية', 'وكالة وفا', 'وكالة معا', 'فضائية النجاح', 'الشرق', 'الشرق الأوسط', 'رويترز', 'سكاي نيوز'
].join(', ');

export const fetchRecentNews = async (customSources: string[]): Promise<RecentNewsItem[]> => {
  try {
    const allSources = [...DEFAULT_SOURCES.split(', '), ...customSources].filter(Boolean).join(', ');
    const prompt = `أوجد لي أهم 5 أخبار باللغة العربية تم نشرها في الساعة الأخيرة من المصادر الإخبارية التالية حصراً: ${allSources}. قدم عنواناً دقيقاً وملخصاً قصيراً لكل خبر.`;

    const model = ai.getGenerativeModel({ model: "gemini-2.5-flash" });
    const response = await model.generateContent(prompt);

    const text = response.response.text();
    const newsItems = text.split(/\n\s*\n/).map(item => {
      const lines = item.split('\n');
      const title = lines[0]?.replace(/^\d+\.\s*\*\*(.*?)\*\*/, '$1').trim() || 'لا يوجد عنوان';
      const snippet = lines.slice(1).join(' ').trim() || 'لا يوجد ملخص.';
      const sourceMatch = snippet.match(/\(المصدر: (.*?)\)/);
      const source = sourceMatch ? sourceMatch[1] : 'مصدر موثوق';
      return { title, snippet, source };
    }).filter(item => item.title !== 'لا يوجد عنوان');

    return newsItems.slice(0, 5);
  } catch (error) {
    console.error("Error fetching recent news:", error);
    throw new Error("فشل في جلب آخر الأخبار.");
  }
};

export const generateNewsFromSource = async (sourceContent: string, instruction: string, mode: GenerationMode): Promise<string> => {
  try {
    let contentInstruction = '';
    if (mode === GenerationMode.URL) {
      const urls = sourceContent.split('\n').filter(url => url.trim().startsWith('http'));
      if (urls.length === 0) throw new Error("الرجاء إدخال رابط واحد على الأقل.");
      contentInstruction = `استنادًا إلى المحتوى الموجود في الروابط التالية حصراً:\n${urls.join('\n')}`;
    } else {
      contentInstruction = `استنادًا إلى النص التالي حصراً:\n---\n${sourceContent}\n---`;
    }

    const prompt = `
      ${contentInstruction}
      
      التعليمات: ${instruction}
      
      بناءً على المصادر المقدمة فقط، اكتب مقالًا إخباريًا احترافيًا ومتكاملًا جاهزًا للنشر على موقع إخباري. يجب أن يتضمن المقال:
      1. **مقدمة قوية**
      2. **جسم المقال**
      3. **خاتمة مناسبة**
      
      الخبر المُعاد صياغته يجب أن يبدأ بـ "رام الله - دوت".
      التزم بالحيادية والموضوعية وتجنب الآراء الشخصية.
    `;

    const model = ai.getGenerativeModel({ model: "gemini-2.5-flash" });
    const response = await model.generateContent(prompt);

    return response.response.text().trim();
  } catch (error) {
    console.error("Error generating news from source:", error);
    throw new Error("فشل في توليد الخبر.");
  }
};

export const generateImage = async (prompt: string): Promise<string> => {
  try {
    const model = ai.getGenerativeModel({ model: "imagen-3.0" });

    const result = await model.generateContent({
      contents: `Generate a realistic, news-style photo: ${prompt}`
    });

    const image = result.response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (!image) throw new Error("No image was generated by the API.");

    return `data:image/jpeg;base64,${image}`;
  } catch (error) {
    console.error("Error generating image:", error);
    throw new Error("فشل في توليد الصورة.");
  }
};

export const generateAllAssets = async (articleText: string): Promise<GeneratedResult> => {
  try {
    const model = ai.getGenerativeModel({ model: "gemini-2.5-flash" });

    const response = await model.generateContent({
      contents: `بناءً على المقال الإخباري التالي حصراً، قم بتوليد مجموعة كاملة من المرفقات الاحترافية المناسبة للنشر على موقع إخباري ومنصات التواصل الاجتماعي. المقال: "${articleText}"`,
      generationConfig: {
        responseMimeType: "application/json",
        responseSchema: {
          type: "object",
          properties: {
            headlineSuggestions: { type: "array", items: { type: "string" } },
            subheadings: { type: "array", items: { type: "string" } },
            imagePrompt: { type: "string" },
            imageCaption: { type: "string" },
            metaDescription: { type: "string" },
            urlSlug: { type: "string" },
            socialCaptions: {
              type: "object",
              properties: {
                facebook: { type: "string" },
                instagram: { type: "string" },
                x_twitter: { type: "string" },
                linkedin: { type: "string" },
                tiktok: { type: "string" },
                snapchat: { type: "string" }
              }
            },
            keyPoints: { type: "array", items: { type: "string" } },
            seoKeywords: { type: "array", items: { type: "string" } },
            infographicSlides: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  title: { type: "string" },
                  content: { type: "string" },
                  icon: { type: "string" }
                }
              }
            }
          }
        }
      }
    });

    const jsonResponse = JSON.parse(response.response.text());

    let generatedImage: string | undefined = undefined;
    if (jsonResponse.imagePrompt) {
      try {
        generatedImage = await generateImage(jsonResponse.imagePrompt);
      } catch (imageError) {
        console.warn("Image generation failed, continuing without image.", imageError);
      }
    }

    return { article: articleText, generatedImage, ...jsonResponse };
  } catch (error) {
    console.error("Error generating all assets:", error);
    throw new Error("فشل في توليد المرفقات التسويقية.");
  }
};

export const translateText = async (text: string): Promise<string> => {
  try {
    const model = ai.getGenerativeModel({ model: "gemini-2.5-flash" });
    const response = await model.generateContent(`Translate the following Arabic text to English: "${text}"`);
    return response.response.text().trim();
  } catch (error) {
    console.error("Error translating text:", error);
    throw new Error("فشل في ترجمة النص.");
  }
};
