import axios from 'axios';
import type { NewsItem, Asset, ParsedNews, Captions, Platform } from '../types';
import { PublishStatus } from '../types';

const api = axios.create({
  baseURL: import.meta.env.VITE_MAIN_BACKEND_URL,
});

api.interceptors.request.use(config => {
  const token = localStorage.getItem('access_token');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

const mapBackendToFrontend = (item: any): NewsItem => {
    const parsed: ParsedNews = {
        headline: item.parsed_data?.headline || item.original_text.substring(0, 70) + '...',
        summary: item.parsed_data?.summary || item.original_text,
        editedSummary: item.edited_text,
        entities: item.parsed_data?.entities || []
    };

    const image: Asset = {
        url: item.image_url || 'https://via.placeholder.com/512.png',
        source: item.image_url ? 'AI Generated' : 'Placeholder',
        query: parsed.headline,
        credit_line: 'Generated by AI',
        license: 'N/A'
    };

    const captions: Captions = (item.posts || []).reduce((acc: any, post: any) => {
        acc[post.platform.toLowerCase() as Platform] = post.content;
        return acc;
    }, {});

    return {
        id: item.id.toString(),
        brandId: item.topic,
        status: item.status || PublishStatus.DRAFT,
        sourceUrl: item.source_url,
        parsed,
        image,
        captions,
        selectedPlatforms: Object.keys(captions) as Platform[],
        createdAt: item.created_at,
    };
};

export const getNewsArticles = async (): Promise<NewsItem[]> => {
  const { data } = await api.get('/api/asharq-automation/articles/');
  return data.map(mapBackendToFrontend);
};

export const processAndGenerate = async (source: { url?: string; text?: string }, platforms: string[], brandId: string): Promise<NewsItem> => {
  const payload = { ...source, platforms, brandId };
  const { data } = await api.post('/api/asharq-automation/articles/process-and-generate/', payload);
  return mapBackendToFrontend(data);
};

export const deleteNewsArticle = async (id: string): Promise<void> => {
  await api.delete(`/api/asharq-automation/articles/${id}/`);
};

// --- هذه هي الدالة المفقودة التي قمنا بإضافتها ---
export const updateNewsArticle = async (id: string, updatedData: Partial<NewsItem>): Promise<NewsItem> => {
    // نرسل فقط البيانات القابلة للتحديث، مثل النصوص والحالة
    const payload = {
        captions: updatedData.captions,
        status: updatedData.status,
        edited_text: updatedData.parsed?.editedSummary,
        image_url: updatedData.image?.url
    };
    const { data } = await api.patch(`/api/asharq-automation/articles/${id}/`, payload);
    // نعيد البيانات المحدثة من الخادم بعد تحويلها
    return mapBackendToFrontend(data);
};