import { Script, TrainingData } from '../types';

// This is a mock service to simulate calling the ChatGPT API.
export const researchWithChatGPT = async (topic: string): Promise<string> => {
  console.log(`Researching with ChatGPT (simulation): ${topic}`);
  await new Promise(resolve => setTimeout(resolve, 1200)); // Simulate longer research
  return `This is a deep research report from ChatGPT on "${topic}". It includes detailed analysis and nuanced perspectives that build upon initial findings.`;
};

export const generateWithChatGPT = async (
  styleName: string,
  title: string,
  duration: string,
  language: string,
  trainingData?: TrainingData
): Promise<Script> => {
  console.log('Generating script with ChatGPT API (simulation)...');
  await new Promise(resolve => setTimeout(resolve, 1000));

  const trainingNotice = trainingData?.instructions
    ? `[تم التوليد بناءً على الإرشادات: ${trainingData.instructions.substring(0, 50)}...]`
    : `[تم التوليد بأسلوب "${styleName}" الإبداعي]`;

  const generatedContent = `[Generated by ChatGPT Engine]
${trainingNotice}

This script for "${title}" has been crafted with the creative flair of ChatGPT.`;

  const mockScript: Script = {
    title: title,
    style: styleName,
    duration: duration,
    content: generatedContent,
    scenes: [
      {
        time: '00:00-02:00',
        description: `Introduction crafted by ChatGPT for ${styleName}`,
        visuals: 'Visually engaging sequences suggested by ChatGPT.',
      },
    ],
    sources: [
      {
        name: 'ChatGPT Generation Engine (Simulated)',
        url: '#',
      },
    ],
  };

  return mockScript;
};
