import axios from 'axios';
import type { NewsItem } from '../types'; // تأكد من أن ملف types.ts لديك صحيح

// يقرأ عنوان الخادم الخلفي الرئيسي من متغيرات البيئة
const api = axios.create({
  baseURL: import.meta.env.VITE_MAIN_BACKEND_URL,
});

// إضافة "بطاقة الهوية" (التوكن) تلقائيًا مع كل طلب
api.interceptors.request.use(config => {
  const token = localStorage.getItem('access_token');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// دالة لتحويل البيانات من الخادم إلى تنسيق الواجهة بأمان
const mapBackendToFrontend = (item: any): NewsItem => {
    return {
        id: item.id.toString(),
        brandId: item.topic,
        status: item.posts?.[0]?.status || 'draft', // يأخذ الحالة من أول منشور
        sourceUrl: item.source_url,
        parsed: {
            headline: item.edited_text?.substring(0, 70) || item.original_text.substring(0, 70) + '...',
            summary: item.original_text,
            editedSummary: item.edited_text,
            entities: [] // يمكن ملؤه لاحقًا
        },
        image: {
            url: item.image_url || 'https://via.placeholder.com/512.png',
            source: item.image_url ? 'AI Generated' : 'Placeholder',
            query: item.edited_text?.substring(0, 50) || 'news image',
            credit_line: 'Generated by AI',
            license: 'N/A'
        },
        captions: (item.posts || []).reduce((acc: any, post: any) => {
            acc[post.platform.toLowerCase()] = post.content;
            return acc;
        }, {}),
        selectedPlatforms: (item.posts || []).map((p: any) => p.platform.toLowerCase()),
        createdAt: item.created_at,
    };
};

export const getNewsArticles = async (): Promise<NewsItem[]> => {
  const { data } = await api.get('/api/asharq-automation/articles/');
  return data.map(mapBackendToFrontend);
};

export const processAndGenerate = async (source: { url?: string; text?: string }, platforms: string[], brandId: string): Promise<NewsItem> => {
  const payload = { ...source, platforms, brandId };
  const { data } = await api.post('/api/asharq-automation/articles/process-and-generate/', payload);
  return mapBackendToFrontend(data);
};

export const deleteNewsArticle = async (id: string): Promise<void> => {
  await api.delete(`/api/asharq-automation/articles/${id}/`);
};

// دالة لتحديث خبر موجود (لحفظ التغييرات من المحرر)
export const updateNewsArticle = async (id: string, updatedData: Partial<NewsItem>): Promise<NewsItem> => {
    // نرسل فقط البيانات التي يمكن للمستخدم تعديلها
    const payload = {
        captions: updatedData.captions,
        status: updatedData.status,
    };
    const { data } = await api.patch(`/api/asharq-automation/articles/${id}/`, payload);
    return mapBackendToFrontend(data);
};

// دالة لإعادة توليد المنشورات لخبر موجود
export const regeneratePostsForArticle = async (articleId: string, platforms: string[]) => {
  const { data } = await api.post(`/api/asharq-automation/articles/${articleId}/generate-posts/`, {
    platforms: platforms,
  });
  return data;
};