# Generated by Django 4.2.24 on 2025-09-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asharq_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='edited_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='generatedpost',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('X', 'X'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('Threads', 'Threads'), ('TikTok', 'TikTok'), ('YouTube_Shorts', 'YouTube Shorts'), ('Telegram', 'Telegram')], max_length=50),
        ),
        migrations.AlterField(
            model_name='generatedpost',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
